name: PR Auto Review with Gemini

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: 
      - develop

permissions:
  contents: read
  pull-requests: write  # PR에 코멘트 작성 권한

jobs:
  gemini-review:
    runs-on: ubuntu-latest
    
    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 전체 히스토리 (diff 계산용)
      
      # 2. Python 환경 설정 (3.12.1)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'
      
      # 3. 필요한 패키지 설치
      - name: Install dependencies
        run: |
          pip install google-generativeai
          pip install PyGithub
      
      # 4. PR 정보 가져오기
      - name: Get PR Info
        id: pr-info
        run: |
          echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          echo "base_sha=${{ github.event.pull_request.base.sha }}" >> $GITHUB_OUTPUT
          echo "head_sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
      
      # 5. Gemini 리뷰 실행
      - name: Run Gemini Review
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.pr-info.outputs.pr_number }}
        run: |
          python scripts/gemini_review.py